# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bded2de490f7103aeb0440cd3bfec6ee69c3b7b2c2b926504bf384e819524335b6675c1a1681533cdbc6fa37045838f391f1540653f12dbb728d0132f2aba60a

test:
  secret_key_base: c93320952b29339a6eef6b7ac9e33efc66a29a7f4091a4c32b09a067262a088d58fd629319005e576b2d90f2ab7d3e40eb30590544ec75a91adb6f41eb080f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
